### ISSUE TITLE
Wrong compatibility flag

### ISSUE THREAD

**Issue by CyrilleB79** [ABuffEr/columnsReview#20]
Ciao Alberto

### Issue
Column review is flagged compatible from NVDA 2017.3 to 2021.1.
However, it is not compatible with NVDA 2019.3.1:

```
ERROR - globalPluginHandler.listPlugins (09:47:59.991) - MainThread (16296):
Error importing global plugin columnsReview
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\columnsReview\globalPlugins\columnsReview\__init__.py", line 34, in <module>
    for r in dir(ct.Role):
AttributeError: module 'controlTypes' has no attribute 'Role'

```

### Solution
Two alternative solutions are possible:
1. Check and fix compatibility on all the range (and now 2022.1)
2. Drop compatibility for older NVDA releases.

Note: In Outlook Extended, I have a `compa.py` module to support compatibility from NVDA 2019.3 onwards regarding `controlTypes` changes.
I plan to extend it to older releases for my NVDA Debug & Test Tools add-on. Let me know in case you are interested.

**Comment by CyrilleB79** [comment]
It was tagged 3.0 but it was probably an old self-built version, not the official one.
I have reinstalled the add-on and the error is gone.
Sorry for inconvenience.
